### ISSUE TITLE
提个建议,卸载的时候不要整个/etc/wireguard目录删掉-【结论：做起来逻辑判断过于复杂，因为有可能第一次通过本脚本安装warp，第二次通过其他脚本安装 wireguard，第三次通过本脚本又安装了client，中间也可能卸载某些。请动手能力强的玩家手动卸载自己不要的部分】

### ISSUE THREAD

**Issue by tofuliang** [fscarmen/warp#143]
我之前自己的wireguard配置被干没了.....

**Comment by fscarmen** [comment]
哈哈，不删除，会对之后重装带来不确定性的影响，因为有原来的配置文件在，我想大多数用户还是希望彻底删除的。如果增加多个确认是否删除 /etc/wireguard/ ，我总觉得会影响用户体验。就这个问题，我先向其他用户了解一下他们有没有这个需求，稍后回复你

**Comment by tofuliang** [comment]
> 哈哈，不删除，会对之后重装带来不确定性的影响，因为有原来的配置文件在，我想大多数用户还是希望彻底删除的。如果增加多个确认是否删除 /etc/wireguard/ ，我总觉得会影响用户体验。就这个问题，我先向其他用户了解一下他们有没有这个需求，稍后回复你

安装的时候可以记录新增了哪些文件,卸载的时候只删除这个列表里的就好了

**Comment by hmsjy2017** [comment]
安装前可以先备份这个目录

**Comment by fscarmen** [comment]
> 安装的时候可以记录新增了哪些文件,卸载的时候只删除这个列表里的就好了

你的情况是在该目录下自己新增了文件，还是在已有的文件上面作编辑更改了？如果是后者，一样照删的哦

**Comment by tofuliang** [comment]
> > 安装的时候可以记录新增了哪些文件,卸载的时候只删除这个列表里的就好了
> 
> 你的情况是在该目录下自己新增了文件，还是在已有的文件上面作编辑更改了？如果是后者，一样照删的哦

安装前已经存在 /etc/wireguard/ 目录,且里面已经有wireguard的配置文件,说起来,我本身已经装了wireguard-tools的包,卸载脚本的时候,也把这个包删掉了.
说白了,就是用脚本前,我已经使用wireguard搭建网络了,卸载脚本时就直接把我之前搭建的网络干掉了.

**Comment by fscarmen** [comment]
现在卸载的逻辑是如果同时安装了 wgcf warp , warp-cli , wireproxy，无论是通过本脚本安装或者是手动安装的，通通卸载掉的。如果需要列清通过本脚本安装的，真只能每一个步骤检测一下系统原来有没有该依赖和文件，逐一记录到一个日志列表里，卸载时只处理那些，感觉有点复杂了。

**Comment by tofuliang** [comment]
> 现在卸载的逻辑是如果同时安装了 wgcf warp , warp-cli , wireproxy，无论是通过本脚本安装或者是手动安装的，通通卸载掉的。如果需要列清通过本脚本安装的，真只能每一个步骤检测一下系统原来有没有该依赖和文件，逐一记录到一个日志列表里，卸载时只处理那些，感觉有点复杂了。 想最小化删除 wgcf warp 的话，你这样操作呢
> 
> ```
> systemctl disable --now wg-quick@wgcf
> rm -rf /etc/wireguard/info.log /etc/wireguard/language /etc/wireguard/menu.sh /etc/wireguard/wgcf-account.toml /etc/wireguard/wgcf.conf /etc/wireguard/wgcf-profile.conf /usr/bin/wgcf
> ```

比全部删掉好🤣

**Comment by fscarmen** [comment]
> > 现在卸载的逻辑是如果同时安装了 wgcf warp , warp-cli , wireproxy，无论是通过本脚本安装或者是手动安装的，通通卸载掉的。如果需要列清通过本脚本安装的，真只能每一个步骤检测一下系统原来有没有该依赖和文件，逐一记录到一个日志列表里，卸载时只处理那些，感觉有点复杂了。 想最小化删除 wgcf warp 的话，你这样操作呢
> > ```
> > systemctl disable --now wg-quick@wgcf
> > rm -rf /etc/wireguard/info.log /etc/wireguard/language /etc/wireguard/menu.sh /etc/wireguard/wgcf-account.toml /etc/wireguard/wgcf.conf /etc/wireguard/wgcf-profile.conf /usr/bin/wgcf
> > ```
> 
> 比全部删掉好🤣

大神，这个好比我们租原来带精装商铺，自己又装修了，经过三五年的经营，期间也有不停的拆拆装装、修修补补。在退租时，房东要还原最终的状态，否则不退押金。这真是要命了。

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/191

**Comment by fscarmen** [comment]
https://github.com/fscarmen/warp/issues/412#issuecomment-1614927141

2023.6.30 menu.sh V3.00 beta one-key script

IMPORTANT:
1. Use Cloudflare official warp api to replace wgcf;
2. Use wireguard-go with reserved to replace kernel. Make Hong Kong, Los Angeles and other restricted areas use warp; The above are the works of Badafans, I would like to thank Badafans and warp-go author coia for their contributions on behalf of all users of this script;
3. Since the changes are too big, please ask users to reinstall, if you have any problems, please feedback, I will deal with it as soon as possible.

重要更新:
1. 全面用 Cloudflare 官方 warp api 替代 wgcf;
2. 使用 wireguard-go with reserved 替代内核。使香港，洛杉矶等受限地区使用 warp; 以上均是大神 badafans 的作品，我谨代表本脚本的所有用户感谢 badafans 和 warp-go 作者 coia 的贡献;
3.由于改动太大，请用户重新安装，如有问题请反馈，我将会尽快处理

这个版本也处理了卸载其他配置文件的问题，现在的逻辑是删除属于本脚本的文件，路径是 /etc/wireguard/，列表如下，之后如果文件夹为空，再行删除目录，即是如果你有其他配置文件，只要不要与下面的文件重名，则不会被删除。

```
wgcf-account.conf
wgcf.conf.bak
wgcf.conf
warp-temp.conf
warp-account.conf
warp_unlock.sh
warp.conf.bak
warp.conf
up
proxy.confbak
proxy.conf
menu.sh
license
language
info-temp.log
info.log
down
account-temp.conf
```
