### ISSUE TITLE
[Feature request]: 希望 warp-go 新增自定义MTU-【结论: 2023年3月2日， V1.1.1 配合着官方 warp-go V1.0.8 版本，自动寻找最佳 MTU，并支持修改】

### ISSUE THREAD

**Issue by luo-die** [fscarmen/warp#287]
### Related Problem / 相关问题

WARP-GO可以正常获取ip WARP因为修改了NAT的MTU导致无法使用

### Describe the solution you want / 描述你希望的解决方案

希望新增自定义MTU

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
已经在 warp-go 项目组反馈，暂时未收到回音。

**Comment by luo-die** [comment]
> 

抱歉描述有误，是希望在warp添加自定义mtu warp-go可以正常获取IP ，我目前所使用的服务器需要保持1280mtu才可以正常上网，warp会修改为1400

**Comment by luo-die** [comment]
对于我描述错误再次表达歉意

**Comment by fscarmen** [comment]
2023.3.2 warp-go 一键脚本 V1.1.1
1. warp-go v1.0.8 is supported. Allowing custom MTU values in the configuration file /opt/warp-go/warp.conf; 

2. Singbox configuration exports reseved using 3-numeric-array instead of a string;

1. 支持 warp-go v1.0.8 , 允许在配置文件 /opt/warp-go/warp.conf 自定义 MTU 值;

2. Singbox配置导出 reseved 使用三个数字的数组代替字符串

```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh
```

**Comment by fscarmen** [comment]
现在 MTU 值是自动寻找最佳值的。如果你仍然有问题，可以 warp-go o 先停了， 修改 /opt/warp-go/warp.conf 里的 MTU，最后 warp-go o 开启。

**Comment by luo-die** [comment]
好的，谢谢您的回答

**Comment by fscarmen** [comment]
> 好的，谢谢您的回答

因为是新版本，需要卸载原来的重新安装

**Comment by luo-die** [comment]
十分感谢
