### ISSUE TITLE
[help wanted 求助]:  失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 

### ISSUE THREAD

**Issue by APPX-Studio** [fscarmen/warp#335]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

<img width="923" alt="image" src="https://user-images.githubusercontent.com/49307767/230722217-fb7a2784-0e11-41a2-af20-bdefb003bd73.png">

### Log / 日志信息

2023-04-08 20:44:00 (46.0 MB/s) - ‘wireguard-go_linux_amd64.tar.gz’ saved [1144803/1144803]

 创建快捷 warp 指令成功 
 运行 WARP 
 后台获取 WARP IP 中,最大尝试5次……
 第1次尝试 

 第2次尝试 
 第3次尝试 
 第4次尝试 
 第5次尝试 
 失败已超过5次，脚本中止，问题反馈:[https://github.com/fscarmen/warp/issues] 
[root@instance-20230408-2012 ~]# 

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
wg-quick up wgcf 看看什么情况

**Comment by APPX-Studio** [comment]
[root@instance-20230408-2012 ~]# wg-quick up wgcf
wg-quick: `wgcf' already exists

**Comment by APPX-Studio** [comment]
> `wg-quick up wgcf` 看看什么情况

**Comment by fscarmen** [comment]
那先 `wg-quick down wgcf` 停了，再 `wg-quick up wgcf`

**Comment by APPX-Studio** [comment]
> 

<img width="832" alt="image" src="https://user-images.githubusercontent.com/49307767/230909736-5ce4d29f-1959-477f-b6a4-20cc0e05ae7e.png">

**Comment by fscarmen** [comment]
> 那先 `wg-quick down wgcf` 停了，再 `wg-quick up wgcf`

执行上面两条，是手动的，看看有什么提示的

**Comment by Desmond-code** [comment]
状态====================== 
脚本版本:2.49
功能新增:1. warp endpoint 优选改为标准端口 [500,1701,2408,4500]; 2. 升级奈飞解锁部分
 系统信息:
	 当前操作系统:Ubuntu 20.04.1 LTS
	 内核:3.10.0-1160.53.1.vz7.185.3
	 处理器架构:amd64
	 虚拟化:openvz 
	 IPv4:      
	 IPv6: 2001:41d0:1004:335b************  法国  OVH SAS 
	 WARP 网络接口未开启 
	 Client 未安装 
	 WireProxy 未安装 
=======================
 1.  为 NAT IPv4 添加 WARP IPv4 网络接口 (bash menu.sh 4) 
 2.  为 NAT IPv4 添加 WARP IPv6 网络接口 (bash menu.sh 6) 
 3.  为 NAT IPv4 添加 WARP 双栈网络接口 (bash menu.sh d) 
 4.  打开 WARP (warp o) 
-----------------------------

选择3之后，会在 - ‘wireguard-go_linux_amd64.tar.gz’ saved [1144803/1144803]   之后卡住
似乎warp没有安装成功

**Comment by Desmond-code** [comment]
> 

root@6283813117woiden:~# wg-quick down wgcf
[#] ip link delete dev wgcf
[#] resolvconf -d wgcf -f
[#] ip -4 rule delete from 192.168.0.111 lookup main
RTNETLINK answers: No such file or directory
root@6283813117woiden:~# wg-quick up wgcf
[#] ip link add wgcf type wireguard
RTNETLINK answers: Operation not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wgcf
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf wgcf /dev/fd/63

**Comment by Desmond-code** [comment]
> > 那先 `wg-quick down wgcf` 停了，再 `wg-quick up wgcf`
> 
> 执行上面两条，是手动的，看看有什么提示的

root@6283813117woiden:~# wg-quick down wgcf
[#] ip link delete dev wgcf
[#] resolvconf -d wgcf -f
[#] ip -4 rule delete from 192.168.0.111 lookup main
RTNETLINK answers: No such file or directory
root@6283813117woiden:~# wg-quick up wgcf
[#] ip link add wgcf type wireguard
RTNETLINK answers: Operation not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wgcf
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf wgcf /dev/fd/63

**Comment by fscarmen** [comment]
我怀疑是 wireguard-go 的版本是最新的问题，按 ctrl + c 之后执行以下的，假设你的 vps 的架构是 amd64的，如果是arm64，只需要把下面的amd64替换成arm64
```
rm -f /usr/bin/wireguard-go; wget -N https://github.com/fscarmen/warp/releases/download/WireGuard-go_v0.0.20201118/wireguard-go_linux_amd64.tar.gz; tar xzf wireguard-go_linux_amd64.tar.gz -C /usr/bin/ ; rm -f wireguard-go_linux_*; chmod +x /usr/bin/wireguard-go
```

**Comment by Desmond-code** [comment]
我尝试warp h的时候出现一下问题：
:~# warp h      
-bash: warp: command not found
===========
这是怎么回事呢？

**Comment by fscarmen** [comment]
由于之前没有安装好，这步没有出来就退出了，刚才是手动运行的，我先换回旧版本的wireguard-go

**Comment by fscarmen** [comment]
> 我尝试warp h的时候出现一下问题：
> warp h
> -bash: warp: command not found
> 这是怎么回事呢？

可以了，你重新下载脚本，使用 `bash menu.sh u` 来卸载，再重新安装即可。

**Comment by zhaozhiming** [comment]
我也是这个问题，请问如何解决？
<img width="900" alt="image" src="https://user-images.githubusercontent.com/1436694/232314412-e1db2c10-2185-4977-8df6-0b3c30becbfb.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/1436694/232314433-53291a38-10e3-41f2-8ce0-345ddd4bc5d2.png">

**Comment by Desmond-code** [comment]
> 我也是这个问题，请问如何解决？ <img alt="image" width="900" src="https://user-images.githubusercontent.com/1436694/232314412-e1db2c10-2185-4977-8df6-0b3c30becbfb.png"> <img alt="image" width="900" src="https://user-images.githubusercontent.com/1436694/232314433-53291a38-10e3-41f2-8ce0-345ddd4bc5d2.png">

先确定warp是否安装正确？命令行键入warp h 回车后有相关信息就算正确把。没有的话重新安装一遍试试。

**Comment by zhaozhiming** [comment]
我warp h 命令是正常的，就是获取不到warp ip

```
warp h
 warp h (帮助菜单）
 warp n (获取 WARP IP)
 warp o (临时warp开关)
 warp u (卸载 WARP 网络接口和 Socks5 Client)
 warp b (升级内核、开启BBR及DD)
 warp a (更换账户为 Free，WARP+ 或 Teams)
 warp p (刷WARP+流量)
 warp v (同步脚本至最新版本)
 warp r (WARP Linux Client 开关)
 warp 4/6 (WARP IPv4/IPv6 单栈)
 warp d (WARP 双栈)
 warp c (安装 WARP Linux Client，开启 Socks5 代理模式)
 warp l (安装 WARP Linux Client，开启 WARP 模式)
 warp i (更换支持 Netflix 的IP)
 warp e (安装 Iptables + dnsmasq + ipset 解决方案)
 warp w (安装 WireProxy 解决方案)
 warp y (WireProxy socks5 开关)
 warp s 4/6/d (优先级: IPv4 / IPv6 / VPS default)
```

**Comment by AoThen** [comment]
手动中止后,执行warp 4看看?
