### ISSUE TITLE
[Bug]: 卸载warp时，删除了其他wireguard配置-【结论：2023年6月30日已处理，只删除本脚本相关的文件】

### ISSUE THREAD

**Issue by koolca** [fscarmen/warp#412]
### Expectation / 预期情况

不应该删除/etc/wireguard文件夹

### Actual Situation / 实际情况

删除了/etc/wireguard文件夹

### Reproduction Method / 复现方法

remove warp

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
找时间处理。

**Comment by fscarmen** [comment]
2023.6.30 menu.sh V3.00 beta one-key script

IMPORTANT:
1. Use Cloudflare official warp api to replace wgcf;
2. Use wireguard-go with reserved to replace kernel. Make Hong Kong, Los Angeles and other restricted areas use warp; The above are the works of Badafans, I would like to thank Badafans and warp-go author coia for their contributions on behalf of all users of this script;
3. Since the changes are too big, please ask users to reinstall, if you have any problems, please feedback, I will deal with it as soon as possible.

重要更新:
1. 全面用 Cloudflare 官方 warp api 替代 wgcf;
2. 使用 wireguard-go with reserved 替代内核。使香港，洛杉矶等受限地区使用 warp; 以上均是大神 badafans 的作品，我谨代表本脚本的所有用户感谢 badafans 和 warp-go 作者 coia 的贡献;
3.由于改动太大，请用户重新安装，如有问题请反馈，我将会尽快处理

这个版本也处理了卸载其他配置文件的问题，现在的逻辑是删除属于本脚本的文件，路径是 /etc/wireguard/，列表如下，之后如果文件夹为空，再行删除目录，即是如果你有其他配置文件，只要不要与下面的文件重名，则不会被删除。

```
wgcf-account.conf
wgcf.conf.bak
wgcf.conf
warp-temp.conf
warp-account.conf
warp_unlock.sh
warp.conf.bak
warp.conf
up
proxy.confbak
proxy.conf
menu.sh
license
language
info-temp.log
info.log
down
account-temp.conf
```
