### ISSUE TITLE
[help wanted 求助]: Why Not Use WireGuard directly?

### ISSUE THREAD

**Issue by jnxyatmjx** [fscarmen/warp#447]
### Script / 脚本

menu.sh

### OS / 操作系统

Ubuntu - Linux

### Actual Situation / 实际情况

When i use command _**wireguard-go**_ in Ubuntu 20.04 LTS . System prompt below：
 Running this software on Linux is unnecessary,  │
│   because the Linux kernel has built-in first     │
│   class support for WireGuard, which will be      │
│   faster, slicker, and better integrated. For     │
│   information on installing the kernel module,    │
│   please visit: <https://wireguard.com/install>.

My Question is why not use kernel **WireGuard** instead of **wireguard-go**

### Log / 日志信息

Nothing

### I confirm that I have updated to the latest version / 我确认已更新至最新版本

- [X] Yes / 是

### I confirm that I have checked the history issues / 我确认已查询历史 issues

- [X] Yes / 是

**Comment by fscarmen** [comment]
> My Question is why not use kernel **WireGuard** instead of **wireguard-go**

Because the wireguard kernel does not support Reserved / Client id, so it can not be used in Hong Kong and Los Angeles and other regions
So we use a third-party version of wireguard-go, and the official difference is the addition of support for Reserved / Client id. Like the following picture:

<img width="928" alt="image" src="https://github.com/fscarmen/warp/assets/62703343/cf60138a-1a83-405f-abb4-55b592d2855b">

**Comment by jnxyatmjx** [comment]
Thanks, got it.

**Comment by fscarmen** [comment]
> Thanks, got it.

2023.7.21 menu.sh V3.00 beta2

1. If the system supports wireguard kernel and wireguard-go-reserved, it can be switched use [warp k], which requires a script reinstallation;
2. Support Fedora system;
3. Fix changing ip error caused by client version 2023.7.40-1.
