### ISSUE TITLE
添加使用kernel wg或wg go的选项-【结论：menu.sh V3.00 beta 2 如果系统支持 wireguard kernel 和 wireguard-go-reserved，可以通过 [warp k] 切换，需要重装脚本】

### ISSUE THREAD

**Issue by Fangliding** [fscarmen/warp#462]
kernel wg和wg go的效率哪个更高还有待商榷 直接全部使用wg go可能不太好 建议在安装的时候询问使用哪个或者在warp菜单里加一个选项 切换至wg go

**Comment by fscarmen** [comment]
现在交互都已经够多了，已经严重影响用户体验了
1. 中英文选择
2. 菜单选择 warp 方案
3. 选择 free / plus / teams 账户
  3.1.1 plus 填 license
  3.1.2 plus 填 设备名
  3.2.1 选择升级 teams 的方式 通过在线文件 / 使用 token / 手动输入 private key / 共享 teams 账户 (默认) 
  3.2.2 下面还分情况填相应的东西。。。。
4. IPv4 / IPv6 优先

计划新增：检测是否有内核（这个lsmod 或者 modprobe 依赖有的系统没有，需要判断是否安装），在有wg内核的情况下
 5. 用wg内核还是 wireguard-go reserved ? 如果我是小白用户，我会崩溃的，怎么TMD这么多东西。每加一个环节，就是增加一个劝退用户的漏斗。 

所以一直没有加这个。

**Comment by fscarmen** [comment]
2023.7.21 menu.sh V3.00 beta2

1. If the system supports wireguard kernel and wireguard-go-reserved, it can be switched use [warp k], which requires a script reinstallation;
2. Support Fedora system;
3. Fix switch error caused by client version 2023.7.40-1

1. 如果系统支持 wireguard kernel 和 wireguard-go-reserved，可以通过 [warp k] 切换，需要重装脚本;
2. 支持 Fedora 系统;
3. 修复 client 2023.7.40-1 版本导致的开关错误

**Comment by GreatMichaelLee** [comment]
建议脚本一开始就询问是否进入专业模式，默认普通模式给小白用，这个flag也可以本地存储持久化避免每次都问

**Comment by fscarmen** [comment]
> 建议脚本一开始就询问是否进入专业模式，默认普通模式就基本功能给小白用，这个flag也可以本地存储持久化避免每次都问

脚本多半是给小白用户使用，太复杂，不但把小白劝退，同时脚本也更多bug了，能免则免了。
